# Generated by Django 5.2.14 on 2026-05-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Foco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel_foco", models.PositiveIntegerField()),
                ("tempo_minutos", models.PositiveIntegerField()),
                ("comentario", models.TextField(blank=True, default=None, null=True)),
                (
                    "categoria",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                ("data", models.DateTimeField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
